### ISSUE TITLE
Module not found: Can't resolve '@tiptap/pm/model'

### ISSUE THREAD

**Issue by anthonykrivonos** [steven-tey/novel#140]
## Issue

Getting the following runtime error when trying to display the text editor:
```
../../.yarn/__virtual__/tiptap-markdown-virtual-6916e9661c/0/cache/tiptap-markdown-npm-0.8.2-404b65508f-339475c9c3.zip/node_modules/tiptap-markdown/dist/tiptap-markdown.esm.js:4:0
Module not found: Can't resolve '@tiptap/pm/model'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
../../.yarn/__virtual__/novel-virtual-f39a532f4d/0/cache/novel-npm-0.1.19-930d72ab54-1372dcaa2c.zip/node_modules/novel/dist/index.mjs
./src/components/editor/MyEditor.tsx
...
```

## Background

My project has the following deps:
```
"novel": "^0.1.19",
"next": "^13.2.4",
"@tiptap/pm": "^2.1.8",
```

## Things I've tried:

1. Installing `@tiptap/pm` manually, as you can see above.
2. Adding `resolutions` in my `.yarnrc` for:
```
"@tiptap/pm@*":
    dependencies:
      prosemirror-changeset: 2.2.1
      prosemirror-collab: 1.3.1
      prosemirror-commands: 1.5.2
      prosemirror-dropcursor: 1.8.1
      prosemirror-gapcursor: 1.3.2
      prosemirror-history: 1.3.2
      prosemirror-inputrules: 1.2.1
      prosemirror-keymap: 1.2.2
      prosemirror-markdown: 1.11.2
      prosemirror-menu: 1.2.2
      prosemirror-model: 1.19.3
      prosemirror-schema-basic: 1.2.2
      prosemirror-schema-list: 1.3.0
      prosemirror-state: 1.4.3
      prosemirror-tables: 1.3.4
      prosemirror-trailing-node: 2.0.7
      prosemirror-transform: 1.7.4
      prosemirror-view: 1.31.7
```
3. Simple stuff like `rm -rf node_modules && yarn cache clean && yarn install`

Thanks in advance.
