### ISSUE TITLE
bug: Placeholder text duplicates on list type items

### ISSUE THREAD

**Issue by kitalee** [steven-tey/novel#490]
### Provide environment information

novel version: 1.0.2

### Describe the bug

Any List types including todo list shows duplicate placeholder texts via '/' key press :

![Image](https://github.com/user-attachments/assets/aa94e3f7-e876-4777-92d5-26ed4743660d)

![Image](https://github.com/user-attachments/assets/7f05e387-8c2d-43d2-887d-fc5806d70297)

### Link to reproduction

https://github.com/steven-tey/novel/releases/tag/novel%401.0.2

### To reproduce

1. Downloaded 1.0.2 zip
2. pnpm i
3. pnpm dev
4. Press '/' and choose any list type item

**Comment by virzs** [comment]
```css
ul[data-type="taskList"]::before,
ul[data-type="taskList"] > li::before,
.list-disc::before,
.list-decimal::before {
  display: none;
}
```
